"""initial schema with pgvector

Revision ID: 5f368ee0298a
Revises: 
Create Date: 2026-03-09 22:55:00.729345+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f368ee0298a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_ns', sa.String(length=255), nullable=False),
    sa.Column('parent_checkpoint_id', sa.String(length=255), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_checkpoints_thread_id'), 'agent_checkpoints', ['thread_id'], unique=False)
    op.create_index('ix_checkpoints_thread_ns', 'agent_checkpoints', ['thread_id', 'checkpoint_ns'], unique=False)
    op.create_table('agent_reasoning_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('internal_monologue', sa.Text(), nullable=False),
    sa.Column('tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_agent_logs_thread_ts', 'agent_reasoning_logs', ['thread_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_agent_reasoning_logs_thread_id'), 'agent_reasoning_logs', ['thread_id'], unique=False)
    op.create_table('critique_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('architect_proposal', sa.Text(), nullable=False),
    sa.Column('auditor_feedback', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critique_history_thread_id'), 'critique_history', ['thread_id'], unique=False)
    op.create_index('ix_critique_thread_round', 'critique_history', ['thread_id', 'round_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('daycare_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vector_store_curriculum',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document', sa.String(length=512), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_curriculum_source_chunk', 'vector_store_curriculum', ['source_document', 'chunk_index'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chat_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_history_thread_created', 'chat_history', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_thread_id'), 'chat_history', ['thread_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.Enum('0-12m', '12-24m', '24-36m', name='age_group_enum'), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_students_age_group', 'students', ['age_group'], unique=False)
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_range', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('theme_emoji', sa.String(length=10), nullable=True),
    sa.Column('palette', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('circle_time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('newsletter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weekly_plans_user_week', 'weekly_plans', ['user_id', 'week_number'], unique=False)
    op.create_table('student_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_embeddings_student_domain', 'student_embeddings', ['student_id', 'domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_embeddings_student_domain', table_name='student_embeddings')
    op.drop_table('student_embeddings')
    op.drop_index('ix_weekly_plans_user_week', table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index('ix_students_user_id', table_name='students')
    op.drop_index('ix_students_age_group', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_chat_history_thread_id'), table_name='chat_history')
    op.drop_index('ix_chat_history_thread_created', table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index('ix_curriculum_source_chunk', table_name='vector_store_curriculum')
    op.drop_table('vector_store_curriculum')
    op.drop_table('users')
    op.drop_index('ix_critique_thread_round', table_name='critique_history')
    op.drop_index(op.f('ix_critique_history_thread_id'), table_name='critique_history')
    op.drop_table('critique_history')
    op.drop_index(op.f('ix_agent_reasoning_logs_thread_id'), table_name='agent_reasoning_logs')
    op.drop_index('ix_agent_logs_thread_ts', table_name='agent_reasoning_logs')
    op.drop_table('agent_reasoning_logs')
    op.drop_index('ix_checkpoints_thread_ns', table_name='agent_checkpoints')
    op.drop_index(op.f('ix_agent_checkpoints_thread_id'), table_name='agent_checkpoints')
    op.drop_table('agent_checkpoints')
    # ### end Alembic commands ###
