"""add unique constraint on weekly_plans user_id week_number

Revision ID: 023b423663bf
Revises: 5f368ee0298a
Create Date: 2026-03-12 06:15:08.223771+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '023b423663bf'
down_revision: Union[str, None] = '5f368ee0298a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_weekly_plans_user_week', 'weekly_plans', ['user_id', 'week_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weekly_plans_user_week', 'weekly_plans', type_='unique')
    # ### end Alembic commands ###
